---
- name: Red Hat One Demo - AI in Ansible
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Network Troubleshooting Assistant
      redhat_one_demo:
        model: gpt-4
        temperature: 0.2
        system_message: >
            As an expert network architect, your role is pivotal in guiding the engineering team through 
            complex design challenges and resolving technical issues with precision. It is imperative 
            that you rigorously review your solutions before finalizing them to avoid any potential errors. 
            In the event of a misconfiguration, it's crucial to rectify and remove it promptly from the 
            device, as leaving such errors unaddressed can lead to significant operational issues. 
            Your expertise and attention to detail are key in maintaining the integrity and efficiency of 
            the network infrastructure.
        prompt: >
            Review the CLI command outputs from network devices at a specific store to pinpoint any irregularities or issues.Your analysis should be succinct, focusing on critical findings that directly impact network functionality or security.

            Output Format:

            Issues Identified: List the primary issues detected, using brief descriptions. Avoid technical jargon where possible, aiming for clarity.

            Suggestions to Fix: Provide straightforward recommendations for each identified issue. Keep suggestions practical and to the point, suitable for immediate action.

            Possible Commands to Fix Issues: Supply a concise list of CLI commands that could rectify the detected problems. Ensure these commands are precise and applicable.

            Present your findings in the outlined format, prioritizing urgent matters. The aim is to equip the network team with clear, direct, and actionable information for updating the ticket and resolving the issues efficiently.
        document: commands_output.txt
      register: ai

    - name: Print AI response
      ansible.builtin.debug:
        msg: "{{ ai['response'] }}"
...
