---
- name: Ansible and AI Playground
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Ansible Assistant
      llm_ollama:
        model: llama-pro
        temperature: 0.3
        system_message: As an expert network architect, you're here to guide engineers through intricate design challenges and effectively resolve issues.
        prompt: Could you provide the commands for configuring VLAN 99 named 'Management' and assigning port fa0/5 to this VLAN, without any explanations?
      register: ai

    - name: Print AI response
      ansible.builtin.debug:
        msg: "{{ ai['response'] }}"
...
